### PR TITLE
Fixed a typo and added lots of payloads

### PR DESCRIPTION
**Pull request by kongwenbin**
Nice and effective tool, good job! 

I was trying to use it but noticed that `spine.py` was unable to find `orpayloads.txt`, so I simply made changes to that one line. 

I have also added a longer list of payloads to the scanner to hopefully make it better.

### CODE REVIEW

**Comment by intercept9** [comment]
Hey thanks on the changes, i am looking to make this multi threaded as i run this on around 1000 subdomains on daily basis and this takes a lot of time for now. Any ideas on that ? also want to know how fast and well this ran for you ? did you face any errors/problems during the execution ?

**Comment by intercept9** [comment]
Hey i knowingly named it "orpayloads" to differentiate between these payloads and other attacks , as i had a plan to write CRLF injection scan, cross site scripting, host header injection etc on the same 😃

**Comment by kongwenbin** [comment]
I see. It runs pretty quickly for me, but I see a few false positives here and there occasionally. Thanks for creating this tool, can't wait to see how it is going to evolve 👍

**Comment by intercept9** [comment]
can you share the false positive results to me,maybe i can figure out the
reason and fix the code

**Comment by kongwenbin** [comment]
Sure. For example, the below URLs leads to a page showing "Not found!", but it was shown in the tool as vulnerable.  

image

image

**Comment by intercept9** [comment]
Ok i get the reason for this,its because the payload has http://google.com
and when appended becomes https://card.io/http://google.com, and the way i
am checking things is checking if http://google.com is present in the final
url so its detecting it vulnerable, a simple cool fix will be to check the
start of the final url to be http://google.com using regex, this will
absolutely fix it, ill do the changes by tonight , thanks :)

**Comment by intercept9** [comment]
Hey, did changes to the code, it should no longer give false positive results , can you validate the same ?

**Comment by kongwenbin** [comment]
Validated and yes, looking good! 👍

**Pull request merged**
